// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema_bodega.Data;

namespace sistema_bodega.Migrations
{
    [DbContext(typeof(BaseDatos))]
    [Migration("20210702064636_reset")]
    partial class reset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("sistema_bodega.Data.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("sistema_bodega.Data.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Rut")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("sistema_bodega.Data.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int>("Umbral")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("sistema_bodega.Data.ProductoBodega", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("BodegaId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("ProductoId", "BodegaId");

                    b.HasIndex("BodegaId");

                    b.ToTable("ProductosBodegas");
                });

            modelBuilder.Entity("sistema_bodega.Data.ProductoBodegaEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BodegaId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosBodegasEmpleados");
                });

            modelBuilder.Entity("sistema_bodega.Data.ProductoBodega", b =>
                {
                    b.HasOne("sistema_bodega.Data.Bodega", "Bodega")
                        .WithMany("ProductoBodegas")
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_bodega.Data.Producto", "Producto")
                        .WithMany("ProductoBodegas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("sistema_bodega.Data.ProductoBodegaEmpleado", b =>
                {
                    b.HasOne("sistema_bodega.Data.Bodega", "Bodega")
                        .WithMany("ProductoBodegaEmpleados")
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_bodega.Data.Empleado", "Empleado")
                        .WithMany("ProductoBodegaEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_bodega.Data.Producto", "Producto")
                        .WithMany("ProductoBodegaEmpleados")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("sistema_bodega.Data.Bodega", b =>
                {
                    b.Navigation("ProductoBodegaEmpleados");

                    b.Navigation("ProductoBodegas");
                });

            modelBuilder.Entity("sistema_bodega.Data.Empleado", b =>
                {
                    b.Navigation("ProductoBodegaEmpleados");
                });

            modelBuilder.Entity("sistema_bodega.Data.Producto", b =>
                {
                    b.Navigation("ProductoBodegaEmpleados");

                    b.Navigation("ProductoBodegas");
                });
#pragma warning restore 612, 618
        }
    }
}
